import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import {
  Play,
  PauseCircle,
  Settings,
  Bot,
  Timer,
  ExternalLink,
} from "lucide-react";
import { toast } from "react-hot-toast";

import { client, nftCollectionAddress } from "../utils/utils.js";
import { uploadJSONToIPFS } from "../utils/uploadToIpfs.ts";
import { useActiveAccount } from "thirdweb/react";
import { WIP_TOKEN_ADDRESS } from "@story-protocol/core-sdk";
import { createHash } from "crypto";

const API_BASE_URL = "https://cultura-e6o8.vercel.app/api";
const CHECK_INTERVAL = 15; // 1 minute in seconds

function AgentDetails() {
  const { id } = useParams();
  const [memeIds, setMemeIds] = useState([]);
  const [loading, setLoading] = useState(true);
  const [agentData, setAgentData] = useState(null);
  const [isAgentActive, setIsAgentActive] = useState(false);
  const [monitoringStats, setMonitoringStats] = useState({});
  const [countdown, setCountdown] = useState(CHECK_INTERVAL);
  const [transactions, setTransactions] = useState([]);
  const [currentlyMonitoring, setCurrentlyMonitoring] = useState("");
  const address = useActiveAccount();
  const [status, setStatus] = useState("Creating derivative...");

  // Fetch all meme IDs from Story Protocol
  const fetchMemeIds = async () => {
    try {
      const response = await fetch("https://api.storyapis.com/api/v3/assets", {
        method: "POST",
        headers: {
          accept: "application/json",
          "X-Api-Key": "MhBsxkU1z9fG6TofE59KqiiWV-YlYE8Q4awlLQehF3U",
          "X-Chain": "story-aeneid",
          "content-type": "application/json",
        },
        body: JSON.stringify({
          options: {
            where: {
              tokenContract: "0x1C7AA3312f8e4dBA6672fAb191AbC007FE01D651",
            },
          },
        }),
      });
      const data = await response.json();
      const ids = data.data.map((item) => item.id);
      console.log("🔍 Found memes to monitor:", ids);
      setMemeIds(ids);
      return ids;
    } catch (error) {
      console.error("Error fetching meme IDs:", error);
      return [];
    }
  };

  // Fetch stats for a single meme
  const fetchMemeStats = async (ipId) => {
    try {
      setCurrentlyMonitoring(ipId);
      const response = await fetch(`${API_BASE_URL}/share-stats/${ipId}`);
      const data = await response.json();
      if (data.success) {
        return data.stats;
      }
      return null;
    } catch (error) {
      console.error(`Error fetching stats for ${ipId}:`, error);
      return null;
    }
  };

  // Find meme with highest engagement
  const findHighestEngagement = (stats) => {
    let highestEngagement = 0;
    let highestIpId = null;

    Object.entries(stats).forEach(([ipId, stat]) => {
      if (!stat) return;
      const totalEngagement = (stat.views || 0) + (stat.shares?.total || 0);
      if (totalEngagement > highestEngagement) {
        highestEngagement = totalEngagement;
        highestIpId = ipId;
      }
    });

    return { ipId: highestIpId, engagement: highestEngagement };
  };

  // License a specific meme
  const licenseMeme = async (ipId, stats) => {
    if (!address || !address.address) {
      toast.error("Please connect your wallet first");
      setIsAgentActive(false); // Stop the agent
      return;
    }
    try {
      console.log(`🎯 Licensing meme with highest engagement:`, {
        ipId,
        stats: stats[ipId],
        totalEngagement:
          (stats[ipId]?.views || 0) + (stats[ipId]?.shares?.total || 0),
      });

      toast.success(
        `Found highest engaging meme: ${ipId}\nViews: ${
          stats[ipId]?.views || 0
        }\nShares: ${stats[ipId]?.shares?.total || 0}`,
        { duration: 5000 }
      );
      console.log(address.address, "is it undefined");
      const derivData = {
        parentIpIds: [ipId],
        licenseTermsIds: [95],
        maxMintingFee: BigInt(0),
        maxRts: 100_000_000,
        maxRevenueShare: 100,
      };

      setStatus("Generating metadata...");

      const ipMetadata = client.ipAsset.generateIpMetadata({
        title: `Derivative Meme from IP:${ipId}`,
        description: "Derivative Meme",
        attributes: [{ key: "Model", value: "dall-e-2" }],
        creators: [
          {
            name: `Derivative Meme generated by ${address.address}`,
            contributionPercent: 100,
            address: address.address,
          },
        ],
      });

      const nftMetadata = {
        name: "Meme Derivative Ownership NFT",
        description: `This NFT represents ownership of the Meme Derivative received by ${address.address}`,
        attributes: [{ key: "Model", value: "dall-e-2" }],
      };

      const ipIpfsHash = await uploadJSONToIPFS(ipMetadata);
      const ipHash = createHash("sha256")
        .update(JSON.stringify(ipMetadata))
        .digest("hex");
      const nftIpfsHash = await uploadJSONToIPFS(nftMetadata);
      const nftHash = createHash("sha256")
        .update(JSON.stringify(nftMetadata))
        .digest("hex");

      setStatus("Creating derivative...");

      const response = await client.ipAsset.mintAndRegisterIpAndMakeDerivative({
        spgNftContract: nftCollectionAddress,
        derivData,
        allowDuplicates: true,
        ipMetadata: {
          ipMetadataURI: `https://ipfs.io/ipfs/${ipIpfsHash}`,
          ipMetadataHash: `0x${ipHash}`,
          nftMetadataURI: `https://ipfs.io/ipfs/${nftIpfsHash}`,
          nftMetadataHash: `0x${nftHash}`,
        },
        txOptions: { waitForTransaction: true },
      });

      setStatus("Processing royalty payment...");
      const payRoyalty = await client.royalty.payRoyaltyOnBehalf({
        receiverIpId: ipId,
        payerIpId: response.ipId,
        token: WIP_TOKEN_ADDRESS,
        amount: 0.03,
        txOptions: { waitForTransaction: true },
      });

      // Add new transaction to history
      const newTransaction = {
        memeId: ipId,
        timestamp: Date.now(),
        status: "Completed",
        txHash: response.txHash,
        ipId: response.ipId,
        tokenId: response.tokenId,
        royaltyTxHash: payRoyalty.txHash,
      };

      setTransactions((prev) => [newTransaction, ...prev]);
      toast.success("Successfully licensed meme!");
    } catch (error) {
      console.error(`Error licensing meme ${ipId}:`, error);
      toast.error(`Failed to license meme ${ipId}`);

      // Add failed transaction to history
      const failedTransaction = {
        memeId: ipId,
        timestamp: Date.now(),
        status: "Failed",
        txHash: "",
        ipId: "",
        tokenId: "",
      };

      setTransactions((prev) => [failedTransaction, ...prev]);
    }
  };

  // Main monitoring function
  const monitorMemes = async () => {
    if (!isAgentActive) return;

    console.log("🤖 Starting monitoring cycle...");
    const ids = await fetchMemeIds();
    console.log(`Found ${ids.length} memes to monitor`);

    const newStats = {};

    // Check all memes
    for (const ipId of ids) {
      console.log(`\n👀 Checking meme ${ipId}...`);
      const stats = await fetchMemeStats(ipId);
      newStats[ipId] = stats;
    }

    setMonitoringStats(newStats);

    // Find and license the meme with highest engagement
    const { ipId, engagement } = findHighestEngagement(newStats);
    if (ipId && engagement > 0) {
      await licenseMeme(ipId, newStats);
    }

    setCurrentlyMonitoring("");
    console.log("✅ Cycle complete - waiting 1 minute before next check");
  };

  // Toggle agent state
  const toggleAgent = async () => {
    if (isAgentActive) {
      setIsAgentActive(false);
      setCurrentlyMonitoring("");
      setCountdown(CHECK_INTERVAL);
      toast.success("Agent monitoring stopped");
    } else {
      setIsAgentActive(true);
      toast.success("Agent monitoring started");
      await monitorMemes();
    }
  };

  // Countdown effect
  useEffect(() => {
    let timer;
    if (isAgentActive) {
      timer = setInterval(() => {
        setCountdown((prev) => {
          if (prev <= 1) {
            monitorMemes();
            return CHECK_INTERVAL;
          }
          return prev - 1;
        });
      }, 1000);
    }

    return () => {
      if (timer) clearInterval(timer);
    };
  }, [isAgentActive]);

  // Initial data fetch
  useEffect(() => {
    const fetchInitialData = async () => {
      try {
        const agentResponse = await fetch(
          `https://api.storyapis.com/api/v3/assets/${id}`,
          {
            headers: {
              accept: "application/json",
              "X-Api-Key": "MhBsxkU1z9fG6TofE59KqiiWV-YlYE8Q4awlLQehF3U",
              "X-Chain": "story-aeneid",
            },
          }
        );
        const agentData = await agentResponse.json();
        setAgentData(agentData.data);
        await fetchMemeIds();
      } catch (error) {
        console.error("Error fetching initial data:", error);
        toast.error("Failed to fetch agent data");
      } finally {
        setLoading(false);
      }
    };

    fetchInitialData();
  }, [id]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-4 border-primary border-t-transparent"></div>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 py-8">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Content - Col span 2 */}
        <div className="lg:col-span-2 space-y-6">
          {/* Agent Status Card */}
          <div className="bg-white rounded-xl shadow-lg p-6">
            <div className="flex justify-between items-center mb-6">
              <div className="flex flex-col space-y-2">
                <h1 className="text-3xl font-bold text-gray-800">AI Agent</h1>
                {agentData && (
                  <div className="text-sm text-gray-600">
                    <p>IP ID: {id}</p>
                    <p>Token ID: {agentData.nftMetadata?.tokenId}</p>
                    <p>Contract: {agentData.nftMetadata?.tokenContract}</p>
                  </div>
                )}
              </div>

              <div className="flex items-center space-x-4">
                {isAgentActive && (
                  <div className="flex items-center space-x-3">
                    <div className="flex items-center space-x-2 bg-blue-100 px-4 py-2 rounded-full">
                      <Timer className="text-blue-500" size={16} />
                      <span className="text-blue-700 font-medium">
                        {Math.floor(countdown / 60)}:
                        {(countdown % 60).toString().padStart(2, "0")}
                      </span>
                    </div>
                    <div className="flex items-center space-x-2 bg-green-100 px-4 py-2 rounded-full">
                      <Bot className="text-green-500 animate-pulse" size={16} />
                      <span className="text-green-700 font-medium">Active</span>
                    </div>
                  </div>
                )}
                <button
                  onClick={toggleAgent}
                  className={`flex items-center px-6 py-3 rounded-lg transition-colors ${
                    isAgentActive
                      ? "bg-red-500 hover:bg-red-600"
                      : "bg-green-500 hover:bg-green-600"
                  } text-white font-medium`}
                >
                  {isAgentActive ? (
                    <>
                      <PauseCircle className="mr-2" size={20} />
                      Stop Agent
                    </>
                  ) : (
                    <>
                      <Play className="mr-2" size={20} />
                      Start Agent
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Meme Stats Display */}
            <div className="mt-6 space-y-4">
              {Object.entries(monitoringStats).map(([ipId, stats]) => (
                <div key={ipId} className="bg-gray-50 p-4 rounded-lg">
                  <h3 className="font-semibold text-lg mb-2">
                    Meme: {ipId.slice(0, 6)}...{ipId.slice(-4)}
                  </h3>
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <p className="text-sm text-gray-500">Views</p>
                      <p className="text-xl font-bold">{stats?.views || 0}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">Shares</p>
                      <p className="text-xl font-bold">
                        {stats?.shares?.total || 0}
                      </p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">Total Engagement</p>
                      <p className="text-xl font-bold text-blue-600">
                        {(stats?.views || 0) + (stats?.shares?.total || 0)}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Transaction History */}
          <div className="bg-white rounded-xl shadow-lg p-6">
            <h2 className="text-xl font-semibold mb-4">Transaction History</h2>
            <div className="space-y-4">
              {transactions.length === 0 ? (
                <p className="text-gray-500 text-center py-4">
                  No transactions yet
                </p>
              ) : (
                transactions.map((tx, index) => (
                  <div key={index} className="border-b pb-4 last:border-b-0">
                    <div className="flex justify-between items-start mb-2">
                      <div>
                        <p className="font-medium">
                          Meme: {tx.memeId.slice(0, 6)}...{tx.memeId.slice(-4)}
                        </p>
                        <p className="text-sm text-gray-500">
                          {new Date(tx.timestamp).toLocaleString()}
                        </p>
                      </div>
                      <span
                        className={`px-3 py-1 rounded-full text-sm ${
                          tx.status === "Completed"
                            ? "bg-green-100 text-green-800"
                            : "bg-red-100 text-red-800"
                        }`}
                      >
                        {tx.status}
                      </span>
                    </div>
                    {tx.status === "Completed" && (
                      <div className="mt-2 space-y-2 text-sm">
                        <div className="flex items-center justify-between">
                          <span className="text-gray-600">License TX:</span>
                          <a
                            href={`https://explorer.goerli.linea.build/tx/${tx.txHash}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex items-center text-blue-600 hover:text-blue-800"
                          >
                            {tx.txHash.slice(0, 6)}...{tx.txHash.slice(-4)}
                            <ExternalLink size={14} className="ml-1" />
                          </a>
                        </div>
                        <div className="flex items-center justify-between">
                          <span className="text-gray-600">IP ID:</span>
                          <span className="font-medium">{tx.ipId}</span>
                        </div>
                        <div className="flex items-center justify-between">
                          <span className="text-gray-600">Token ID:</span>
                          <span className="font-medium">{tx.tokenId}</span>
                        </div>
                        {tx.royaltyTxHash && (
                          <div className="flex items-center justify-between">
                            <span className="text-gray-600">Royalty TX:</span>
                            <a
                              href={`https://explorer.goerli.linea.build/tx/${tx.royaltyTxHash}`}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="flex items-center text-blue-600 hover:text-blue-800"
                            >
                              {tx.royaltyTxHash.slice(0, 6)}...
                              {tx.royaltyTxHash.slice(-4)}
                              <ExternalLink size={14} className="ml-1" />
                            </a>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        {/* Monitoring Status */}
        <div className="bg-white rounded-xl shadow-lg p-6 h-fit">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold">Monitoring Status</h2>
            <Settings size={20} className="text-gray-500" />
          </div>

          <div className="space-y-4">
            <div className="p-4 bg-gray-50 rounded-lg">
              <p className="text-sm text-gray-600 mb-2">
                Currently Monitoring:
              </p>
              <p className="font-medium">
                {currentlyMonitoring ? (
                  <>
                    Meme: {currentlyMonitoring.slice(0, 6)}...
                    {currentlyMonitoring.slice(-4)}
                  </>
                ) : (
                  "Waiting for next cycle..."
                )}
              </p>
            </div>

            <div className="p-4 bg-gray-50 rounded-lg">
              <p className="text-sm text-gray-600 mb-2">Check Interval:</p>
              <p className="font-medium">Every 60 seconds</p>
            </div>

            <div className="p-4 bg-gray-50 rounded-lg">
              <p className="text-sm text-gray-600 mb-2">Total Memes Tracked:</p>
              <p className="font-medium">{memeIds.length}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AgentDetails;
